### ISSUE TITLE
Thêm các model

### ISSUE THREAD

**Issue by pesuyn** [pesuyn/SE05-Nhom09#12]
Sử dụng blender tạo mẫu và chỉnh lại kích thước bị sai

**Comment by xoatrag** [comment]
Checked

**Comment by viethq00** [comment]
Đã thêm các model cat2, dog, fox_face_mesh_texture, freckles1, freckles2, glasses2, glasses3, glasses4, glasses5, hair, hat, hat1, hat2, mask1, mask2, mask3
