### ISSUE TITLE
Dùng session để reset camera

### ISSUE THREAD

**Issue by pesuyn** [pesuyn/SE05-Nhom09#14]
Dùng session để reset camera

**Comment by huuquang12** [comment]
Hãy thử đọc ví dụ này xem sao.
https://stackoverflow.com/questions/5658675/replacing-a-fragment-with-another-fragment-inside-activity-group

**Comment by huuquang12** [comment]
Hướng dẫn reset session 
https://github.com/google-ar/sceneform-android-sdk/issues/492

**Comment by pesuyn** [comment]
Đã hoàn thành
